// module.exports.authService = require('./auth.service');
// module.exports.emailService = require('./email.service');
// module.exports.tokenService = require('./token.service');
// module.exports.userService = require('./user.service');
module.exports.amqSettingService = require('./amqSetting.service');
module.exports.databaseSettingService = require('./databaseSetting.service');
module.exports.displaySettingService = require('./displaySetting.service');
module.exports.localeSettingService = require('./localeSetting.service');
module.exports.logSettingService = require('./logSetting.service');
module.exports.reportSettingService = require('./reportSetting.service');
module.exports.securitySettingService = require('./securitySetting.service');
module.exports.formsService = require('./forms.service');
module.exports.formValidationService = require('./formValidation.service')
module.exports.reasonService = require('./reason.service')
module.exports.pullModeListService = require('./pull-mode-list.service')
module.exports.agentDeskSettingsService = require('./agentDeskSettings.service');
module.exports.healthCheckService = require('./healthCheck.service');
